[build]
  command = "npm run build"
  publish = "dist/actify/browser"
  functions="netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200