[build]
  command = "npm run build"
  publish = "dist/actify"
  functions="netlify/functions"

[build.environment]
  NETLIFY_USE_ANGULAR_RUNTIME = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200