[build]
  command = "npm run build"
  publish = "dist/actify"
  functions="netlify/functions"

[context.production]
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200